
## Generator

```
function\* gen() {
  var y = yield x + 2;
  return y;
}
```
- generator函数返回的是个指针对象（即遍历器）g。
调用指针g.next()方法，会移动指针到generator内的某段代码语句，并执行。代码语句通过yeild关键字分段。换言之，next 方法的作用是分阶段执行 Generator 函数。每次调用 next 方法，会返回一个对象，表示当前阶段的信息（ value 属性和 done 属性）。

- value 属性是 yield 语句后面表达式的值，表示当前阶段的值；done 属性是一个布尔值，表示 Generator 函数是否执行完毕，即是否还有下一个阶段。

- next 方法还可以接受参数，这是向 Generator 函数体内输入数据。
```
function* gen(x){
  try {
    var y = yield x + 2;
  } catch (e){ 
    console.log(e);
  }
  return y;
}

var g = gen(1);
g.next();
g.throw（'出错了'）;
// 出错了
```

- Generator 函数体外，使用指针对象的 throw 方法抛出的错误，可以被函数体内的 try ... catch 代码块捕获。
**出错的代码与处理错误的代码，实现了时间和空间上的分离，这对于异步编程无疑是很重要的。**

## Thunk函数
编译器 - 传值调用 (call by value);传名调用 (call by name)

- 编译器的"传名调用"实现，往往是将参数放到一个临时函数之中，再将这个临时函数传入函数体。这个临时函数就叫做 Thunk 函数。

```
function f(m){
  return m * 2;     
}

f(x + 5);

// 等同于

var thunk = function () {
  return x + 5;
};

function f(thunk){
  return thunk() * 2;
}
```
# promise详解
[https://www.yuque.com/ostwind/es6/docs-async](https://www.yuque.com/ostwind/es6/docs-async)
- async-await
```
function timeout(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve(1), ms);
  });
}
// async返回值是一个promise
async function asyncPrint(value, ms) {
  try {
    const res = await timeout(ms); // await 后面是一个promise，返回值就是Promise.resolve的值
    console.log(res)
  } catch (err) { // 有必要加错误处理，否则promise如果reject的话，会直接中断后面的执行，转至async函数返回的promise内的catch回调
    console.log(err)
  }
  console.log(value);
}

asyncPrint('hello world', 50).catch(err => {  // async函数返回的是个promise对象
	console.log(err)
});
```


- 按次序输出
1. promise实现
```
function logInOrder(urls) {
  // 远程读取所有URL
  const textPromises = urls.map(url => {
    return fetch(url).then(response => response.text());
  });


  // 按次序输出, 活用reduce写promise按顺序请求
  textPromises.reduce((chain, textPromise) => {
    return chain.then(() => textPromise)
      .then(text => console.log(text));
  }, Promise.resolve());
} 
```
2. async-await实现
```
// 注意看await与循环的关系
async function logInOrder(urls) {
  for (const url of urls) {
    const response = await fetch(url);
    console.log(await response.text());
  }
}
// 上面的代码，只有前一个 URL 返回结果，才会去读取下一个 URL，请求并没有并发
async function logInOrder(urls) {
  // 并发读取远程URL
  const textPromises = urls.map(async url => {
    const response = await fetch(url);
    return response.text();
  });
  // 按次序输出
  for (const textPromise of textPromises) {
    console.log(await textPromise);
  }
}

//上面代码中，虽然map方法的参数是async函数，但它是并发执行的，因为只有async函数内部是继发执行，外部不受影响。后面的for..of循环内部使用了await，因此实现了按顺序输出。
// 理解上可以认为textPromises是个数组，由多个promise组成，promise就是内部async函数返回的promise，此时在通过后续的for..of循环结合await就可以实现按次序输出的效果

```